//Auto-generated by RSP Compiler
//Source: shutdownPlain.rsp.html
library shutdownPlain_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, shutdownPlainView, for rendering the view. */
Future shutdownPlainView(HttpConnect connect, {reason}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");

  response.write("""<div class="content">
    <h1>Stránka je vypnutá</h1>
    <p>
        """);

  response.write(Rsp.nnx(reason));


  response.write("""

    </p>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
