name: bakalari_webapp
version: 0.9.0
author: Petr Šťastný <petr.stastny01@gmail.com>
homepage: https://github.com/SoptikHa2/bakalari_webapp
environment:
        sdk: '>=2.1.0 <3.0.0'
dependencies:
        bakalari: ^0.3.2 # The library for querying school servers
        stream: ^2.2.1 # Web framework
        sembast: ^1.15.4 # Web framework
        uuid: ^2.0.1 # UUID generator
        markdown: ^2.0.3 # For conversion from markdown to html (contact)
        encrypt: ^2.0.0 # For encryption of student data
        dotp: ^1.0.2 # For 2fa verification
        json_serializable: ^3.0.0 # For serialization to/from JSON (DB, api)

dev_dependencies:
        build_runner: ^1.4.0
