name: bakalari_webapp
version: 0.9.0
author: Petr Šťastný <petr.stastny01@gmail.com>
homepage: https://github.com/SoptikHa2/bakalari_webapp
environment:
        sdk: '>=2.1.0 <3.0.0'
dependencies:
        bakalari: ^0.2.2
        stream: ^2.1.0
        sembast: ^1.12.0+1
        uuid: ^1.0.3

dev_dependencies:
        json_serializable: ^2.0.1
        build_runner: ^1.1.2
        dotp: ^1.0.2
