//Auto-generated by RSP Compiler
//Source: privacyPolicyView.rsp.html
library privacyPolicyView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, privacyPolicyView, for rendering the view. */
Future privacyPolicyView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("webapp/view/head.html");

  response.write("""<div class="content">
  Lorem Ipsum
</div>
""");

  await connect.include("webapp/view/tail.html");

  return null;
}
