//Auto-generated by RSP Compiler
//Source: privacyPolicyView.rsp.html
library privacyPolicyView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, privacyPolicyView, for rendering the view. */
Future privacyPolicyView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("webapp/view/head.html");

  response.write("""<div class="content">
  <h1>Ochrana osobních údajů</h1>
  <p>
    Přihlášením na web předáváte své přihlašovací údaje na zpracování tomuto serveru. Dlouhodobě jsou však uloženy
    pouze ve Vašem prohlížeči ve formě cookie, server k nim má přístup pouze po dobu zpracování Vašeho požadavku.
    Kliknutím na tlačítko odhlásit jsou údaje odstraňeny i z Vašeho prohlížeče.
  </p>
  <p>
    Dočasně ukládáme na serveru informace přijaté ze serveru školy, abychom je mohli průběžně zobrazovat a nemuseli jste
    při každém dalším načtení stránky znovu zadávat heslo.
  </p>
  <p>
    Zároveň zaznamenáváme informace o přístupu a využívání těchto webových stránek kvůli analýze
    návštěvnosti těchto webových stránek a způsobu jejich využívání.
  </p>
</div>
""");

  await connect.include("webapp/view/tail.html");

  return null;
}
