//Auto-generated by RSP Compiler
//Source: rootView.rsp.html
library rootView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, rootView, for rendering the view. */
Future rootView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("webapp/view/head.html");

  response.write("""<div class="main">
""");

  if (connect.dataset['status'] == 0) {

    response.write("""  <!-- Login form (user is logged out) -->
""");

  } else if (connect.dataset['status'] == 1) {

    response.write("""  <!-- Refresh button (user logged in recently) -->
""");
  } //if

  response.write("""</div>
""");

  await connect.include("webapp/view/tail.html");

  return null;
}
