//Auto-generated by RSP Compiler
//Source: studentView.rsp.html
library studentView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, studentView, for rendering the view. */
Future studentView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("webapp/view/head.html");

  response.write(Rsp.nnx(connect.request.method));


  response.write("""

""");

  await connect.include("webapp/view/tail.html");

  return null;
}
