//Auto-generated by RSP Compiler
//Source: messageListView.rsp.html
library messageListView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, messageListView, for rendering the view. */
Future messageListView(HttpConnect connect, {List<dynamic> messages, List<String> strippedMessagesContent, List<String> datetimesFormatted, String sendMessageLink}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/studentHead.html");

  response.write("""        <div class="content">
            <h1 class="content-subhead">Přijaté zprávy</h1>
            <a href=\"""");

  response.write(Rsp.nnx(sendMessageLink));


  response.write("""" target="_blank">Odeslat zprávu z oficiální aplikace</a>
""");
var i = 0;

  response.write("""

""");

  for (var message in messages) {

    response.write("""            <div class="listDiv">
                <h2 class="content-subhead">""");

    response.write(Rsp.nnx(message.senderName));


    response.write("""</a></h2>
                <p style="float: right; margin-top: -2.6em;">
                    """);

    response.write(Rsp.nnx(datetimesFormatted[i]));


    response.write("""

                </p>
                <article>
                    <p>
                        """);

    response.write(Rsp.nnx(strippedMessagesContent[i++]));


    response.write(""" 
                    </p>
                </article> 
                    <p>
                            <a href="/student/message/""");

    response.write(Rsp.nnx(message.id));


    response.write(""""><button class="pure-button">Zobrazit</button></a>
                    </p>
            </div>
""");
  } //for

  response.write("""        </div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
