//Auto-generated by RSP Compiler
//Source: messageDetailsView.rsp.html
library messageDetailsView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, messageDetailsView, for rendering the view. */
Future messageDetailsView(HttpConnect connect, {dynamic message, String datetimeFormatted}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/studentHead.html");

  response.write("""<div class="content">
    <h1 class="content-subhead">""");

  response.write(Rsp.nnx(message.senderName));


  response.write("""</h1>
    <p style="float: right; margin-top: -2.6em;">
        """);

  response.write(Rsp.nnx(datetimeFormatted));


  response.write("""

    </p>
    <article>
        <p>
            """);

  response.write(Rsp.nnx(message.content, encode: 'none'));


  response.write("""

        </p>
    </article>
    <p>
        <a href="/student/message"><button class="pure-button">Zpět</button></a>
    </p>
</div>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
