//Auto-generated by RSP Compiler
//Source: refreshStudentInfoView.rsp.html
library refreshStudentInfoView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, refreshStudentInfoView, for rendering the view. */
Future refreshStudentInfoView(HttpConnect connect, {List<String> urls, String errorDescription, String presetUrl, String
    presetUsername}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/studentHead.html");

  response.write("""    <div class="content">
""");

  if (errorDescription != null) {

    response.write("""        <aside class="errorBar">
            <p>
                """);

    response.write(Rsp.nnx(errorDescription));


    response.write("""

            </p>
        </aside>
""");
  } //if

  response.write("""

        <form class="pure-form" action="/student?refresh=1" method="POST">
            <fieldset>
                <legend>Obnovení údajů o studentovi (<a href="/privacy_policy">zpracování osobních údajů</a>)</legend>

                <label for="urlSelectField">Zadejte jméno školy nebo URL přihlašovací stránky</label>
                <input name="bakawebUrl" id="urlSelectField" type="text" placeholder="Českolipská" """);

  response.write(Rsp.nnx(presetUrl !=null
                    ? 'value=$presetUrl' : ''));


  response.write(""" />
                <div id="schoolList" class="schoolList">

                </div>
                <input name="login" type="text" placeholder="Uživatelské jméno" """);

  response.write(Rsp.nnx(presetUsername !=null
                    ? 'value=$presetUsername' : ''));


  response.write(""">
                <input name="password" type="password" placeholder="Heslo">

                <button type="submit" class="pure-button pure-button-primary">Přihlásit</button>
            </fieldset>
        </form>
        <p>
            Po zadání přihlašovacích údajů do formuláře ze serverů školy stáhneme a zobrazíme nejnovější data.
        </p>
    </div>
  <script src="/js/selectSchoolFromList.js"></script>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
