//Auto-generated by RSP Compiler
//Source: studentTimetableView.rsp.html
library studentTimetableView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, studentTimetableView, for rendering the view. */
Future studentTimetableView(HttpConnect connect, {dynamic timetable, dynamic nextWeekTimetable, dynamic permanentTimetable}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/studentHead.html");
String nbsp = "\u{00A0}";

  response.write("""


<div class="content">
    <noscript>
        <p>
            Zapněte JavaScript pro možnost změny náhledu rozvrhu.
        </p>
    </noscript>
    <h1>Rozvrh</h1>
    <a href="/student">Zpět</a> <br />
    <button class="pure-button pure-button-secondary" onclick="switchtimetableDisplay('tabletoday')">Tento týden</button>
    <button class="pure-button pure-button-secondary" onclick="switchtimetableDisplay('tabletomorrow')">Příští týden</button>
    <button class="pure-button pure-button-secondary" onclick="switchtimetableDisplay('tablepermanent')">Trvalý rozvrh</button>
""");

  if (timetable != null) {

    response.write("""    <div class="smallscreen-div-y-scrollable">
        <table class="pure-table" id="tabletoday">
            <thead>
                <tr></tr>
                <tr>
                    <th></th>
""");

    for (var hour in timetable.times) {

      response.write("""                    <th title=\"""");

      response.write(Rsp.nnx(hour.beginTime));


      response.write(""" - """);

      response.write(Rsp.nnx(hour.endTime));


      response.write("""">
                        """);

      response.write(Rsp.nnx(hour.caption));


      response.write("""

                    </th>
""");
    } //for

    response.write("""                </tr>
            </thead>
            <tbody>
""");

    for (var day in timetable.days) {

      response.write("""                <tr>
                    <th>""");

      response.write(Rsp.nnx(day.shortName));


      response.write("""</th>
""");

      for (var lessons in day.lessons) {

        response.write("""                    <td class="table-cell-small">
""");

        for (var lesson in lessons) {

          response.write("""                        <div class="table-cell-standalone """);

          response.write(Rsp.nnx((lesson.change != null && lesson.change != '') ? 'background-alert' : ''));


          response.write("""">
                            <div class="table-cell-main">""");

          response.write(Rsp.nnx(lesson.subjectShort));


          response.write("""</div>
                            <span class="table-cell-secondary">""");

          response.write(Rsp.nnx(lesson.teacherShort));


          response.write(Rsp.nnx((lesson.teacherShort ==
                                null
                                || lesson.teacherShort == "" || lesson.classroom == null || lesson.classroom == "")
                                ?
                                '' : '$nbsp|$nbsp'));


          response.write(Rsp.nnx(lesson.classroom));


          response.write("""</span>
                        </div>
""");
        } //for

        response.write("""                    </td>
""");
      } //for

      response.write("""                </tr>
""");
    } //for

    response.write("""            </tbody>
        </table>
    </div>
""");
  } //if

  if (nextWeekTimetable != null) {

    response.write("""    <div class="smallscreen-div-y-scrollable">
        <table class="pure-table" id="tabletomorrow">
            <thead>
                <tr></tr>
                <tr>
                    <th></th>
""");

    for (var hour in nextWeekTimetable.times) {

      response.write("""                    <th title=\"""");

      response.write(Rsp.nnx(hour.beginTime));


      response.write(""" - """);

      response.write(Rsp.nnx(hour.endTime));


      response.write("""">
                        """);

      response.write(Rsp.nnx(hour.caption));


      response.write("""

                    </th>
""");
    } //for

    response.write("""                </tr>
            </thead>
            <tbody>
""");

    for (var day in nextWeekTimetable.days) {

      response.write("""                <tr>
                    <th>""");

      response.write(Rsp.nnx(day.shortName));


      response.write("""</th>
""");

      for (var lessons in day.lessons) {

        response.write("""                    <td class="table-cell-small">
""");

        for (var lesson in lessons) {

          response.write("""                        <div class="table-cell-standalone """);

          response.write(Rsp.nnx((lesson.change != null && lesson.change != '') ? 'background-alert' : ''));


          response.write("""">
                            <div class="table-cell-main">""");

          response.write(Rsp.nnx(lesson.subjectShort));


          response.write("""</div>
                            <span class="table-cell-secondary">""");

          response.write(Rsp.nnx(lesson.teacherShort));


          response.write(Rsp.nnx((lesson.teacherShort ==
                                null
                                || lesson.teacherShort == "" || lesson.classroom == null || lesson.classroom == "")
                                ?
                                '' : '$nbsp|$nbsp'));


          response.write(Rsp.nnx(lesson.classroom));


          response.write("""</span>
                        </div>
""");
        } //for

        response.write("""                    </td>
""");
      } //for

      response.write("""                </tr>
""");
    } //for

    response.write("""            </tbody>
        </table>
    </div>
""");
  } //if

  if (permanentTimetable != null) {

    response.write("""    <div class="smallscreen-div-y-scrollable">
        <table class="pure-table" id="tablepermanent">
            <thead>
                <tr></tr>
                <tr>
                    <th></th>
""");

    for (var hour in permanentTimetable.times) {

      response.write("""                    <th title=\"""");

      response.write(Rsp.nnx(hour.beginTime));


      response.write(""" - """);

      response.write(Rsp.nnx(hour.endTime));


      response.write("""">
                        """);

      response.write(Rsp.nnx(hour.caption));


      response.write("""

                    </th>
""");
    } //for

    response.write("""                </tr>
            </thead>
            <tbody>
""");

    for (var day in permanentTimetable.days) {

      response.write("""                <tr>
                    <th>""");

      response.write(Rsp.nnx(day.shortName));


      response.write("""</th>
""");

      for (var lessons in day.lessons) {

        response.write("""                    <td class="table-cell-small">
""");

        for (var lesson in lessons) {

          response.write("""                        <div class="table-cell-standalone """);

          response.write(Rsp.nnx((lesson.change != null && lesson.change != '') ? 'background-alert' : ''));


          response.write("""">
                            <div class="table-cell-main">""");

          response.write(Rsp.nnx(lesson.subjectShort));


          response.write("""</div>
                            <span class="table-cell-secondary">""");

          response.write(Rsp.nnx(lesson.teacherShort));


          response.write(Rsp.nnx((lesson.teacherShort ==
                                null
                                || lesson.teacherShort == "" || lesson.classroom == null || lesson.classroom == "")
                                ?
                                '' : '$nbsp|$nbsp'));


          response.write(Rsp.nnx(lesson.classroom));


          response.write("""</span>
                        </div>
""");
        } //for

        response.write("""                    </td>
""");
      } //for

      response.write("""                </tr>
""");
    } //for

    response.write("""            </tbody>
        </table>
    </div>
""");
  } //if

  response.write("""</div>

<script src="/js/switchTimetableDisplay.js"></script>
<script>
// By default show this week timetable
switchtimetableDisplay('tabletoday');
</script>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
