//Auto-generated by RSP Compiler
//Source: studentView.rsp.html
library studentView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, studentView, for rendering the view. */
Future studentView(HttpConnect connect, {String errorDescription, dynamic timetableRow, dynamic averages,
String lastRefresh,
String lastMailInfo, String urgentAbsence, String urgentHomeworks}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/studentHead.html");

  response.write("""<div class="content">
""");

  if (errorDescription != null) {

    response.write("""    <aside class="errorBar">
        <p>
            """);

    response.write(Rsp.nnx(errorDescription));


    response.write("""

        </p>
    </aside>
""");
  } //if

  response.write("""    <noscript>
        <aside class="errorBar">
            <p>
                Nemáte zapnutý JavaScript, stránka tedy sama nenačítá
                přijaté informace. Můžete je načíst manuálně obnovením
                stránky (F5)
            </p>
        </aside>
    </noscript>
    <div id="failed-to-fetch-update" style="display: none">
        <aside class="errorBar">
            <p>
                Připojení k serveru školy proběhlo úspěšně, ale něco
                se nepodařilo načíst. Na této stránce se zobrazí vše,
                co se nám podařilo načíst. Pokud tento stav přetrvává,
                <a href="/contact">kontaktujte vývojáře</a>.
            </p>
        </aside>
    </div>
    <div class="pure-g" id="main">
        <div class="pure-u-1 pure-u-md-1-2" id="timetable">
""");

  if (timetableRow == null) {

    response.write("""            <h1 class="content-subhead">Rozvrh</h1>
            <p class="loader">
                Načítám rozvrh, za chvíli tady bude...
            </p>
""");

  } else {

    response.write("""            <h1 class="content-subhead">""");

    response.write(Rsp.nnx((timetableRow.date as DateTime).weekday == DateTime.now().weekday ? 'Dnes' :
                ((timetableRow.date.weekday - 1) - DateTime.now().weekday < 1 ? 'Zítra' : timetableRow.shortName)));


    response.write("""</h1>
                    <table class="pure-table">
                    <tbody>
""");

    for (var multipleLessons in timetableRow.lessons) {

      for (var lesson in multipleLessons) {

        response.write("""                        <tr class=\"""");

        response.write(Rsp.nnx(lesson.change != null && lesson.change != '' ? 'lesson-change' : ''));


        response.write("""">
                            <td>
                                """);

        response.write(Rsp.nnx(lesson.lessonTime.caption));


        response.write("""

                            </td>
""");

        if (lesson.isSet != null && lesson.isSet) {

          response.write("""                            <td>
                                """);

          response.write(Rsp.nnx(lesson.subjectLong));


          response.write(""" (""");

          response.write(Rsp.nnx(lesson.teacherShort));


          response.write(""")
                            </td>
                            <td>
                                """);

          response.write(Rsp.nnx(lesson.classroom));


          response.write("""

                            </td>
""");

        } else {

          response.write("""                            <td></td>
                            <td></td>
""");
        } //if

        response.write("""                        </tr>
""");
      } //for
    } //for

    response.write("""                    </tbody>
                    </table>
""");
  } //if

  response.write("""        </div>
        <div class="pure-u-1 pure-u-md-1-2" id="grades">
            <h1 class="content-subhead">Průměry</h1>
""");

  if (averages == null) {

    response.write("""            <p class="loader">
                Načítám známky, za chvíli to bude...
            </p>
""");

  } else {

    response.write("""            <table class="pure-table">
                <tbody>
""");

    for (var subject in averages.keys) {

      response.write("""                    <tr>
                        <td>
                            <a href="/student/subject/""");

      response.write(Rsp.nnx(subject));


      response.write("""">""");

      response.write(Rsp.nnx(subject));


      response.write("""</a>
                        </td>
                        <td>
                            """);

      response.write(Rsp.nnx(averages[subject].toStringAsPrecision(3)));


      response.write("""

                        </td>
                    </tr>
""");
    } //for

    response.write("""                </tbody>
            </table>
""");
  } //if

  response.write("""        </div>
        <div class="pure-u-1 pure-u-md-1" id="otherModules">
            <h1 class="content-subhead">Ostatní</h1>
            <ul>
                <li>
                    <a href="/student/timetable">Rozvrh</a>
                </li>
                <li>
                    Přehled zpráv
                    """);

  response.write(Rsp.nnx(lastMailInfo == null ? '' : '(poslední zpráva $lastMailInfo)'));


  response.write("""

                </li>
                <li>
                    Přehled absencí
                    """);

  response.write(Rsp.nnx(urgentAbsence == null ? '' : urgentAbsence));


  response.write("""

                </li>
                <li>
                    Přehled domácích úkolů
                    """);

  response.write(Rsp.nnx(urgentHomeworks == null ? '' : urgentHomeworks));


  response.write("""

                </li>
                <hr />
                <li>
                    <a href="/refresh">Načíst nejnovější data</a>
                </li>
                <li>
                    <a href="/logout">Odhlásit se</a>
                </li>
            </ul>
        </div>
    </div>
</div>
""");

  if (lastRefresh != null) {

    response.write("""<p style="text-align: center">
    To co vidíte na této stránce je """);

    response.write(Rsp.nnx(lastRefresh));


    response.write(""" staré.
    <a href="/refresh"><button class="pure-button">Obnovit</button></a>
</p>
""");
  } //if

  response.write("""

<script>
    if ('serviceWorker' in navigator) {
        navigator.serviceWorker
            .register('/offlineServiceWorker.js')
            .then(function () { console.log("Service Worker Registered"); });
    }
</script>
<script src="../../js/studentRefresh.js"></script>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
