//Auto-generated by RSP Compiler
//Source: adminGodView.rsp.html
library adminGodView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, adminGodView, for rendering the view. */
Future adminGodView(HttpConnect connect, {dynamic students, dynamic classes}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/adminHead.html");

  response.write("""<div class="content">
    <h1>Debug - student</h1>
    <form class="pure-form" action="/admin/god/student" method="GET">
        <fieldset>
            <legend>Vyberte studenta</legend>
            <input name="student" type="text" list="students" autocomplete="off">
            <datalist id="students">
""");

  for (var student in students) {

    response.write("""                <option>""");

    response.write(Rsp.nnx(student.studentInfo.name.replaceAll(' ',
                    '-')));


    response.write("""-""");

    response.write(Rsp.nnx(student.studentInfo.schoolClass));


    response.write("""-""");

    response.write(Rsp.nnx(student.schoolInfo.name.replaceAll(' ', '-')));


    response.write("""</option>
""");
  } //for

  response.write("""            </datalist>
            <button type="submit" class="pure-button pure-button-primary">Zobrazit</button>
        </fieldset>
    </form>
    <h1>Debug - class</h1>
    <form class="pure-form" action="/admin/god/class" method="GET">
        <fieldset>
            <legend>Vyberte třídu</legend>
            <input name="class" type="text" list="classes" autocomplete="off">
            <datalist id="classes">
""");

  for (var cl in classes) {

    response.write("""                <option>""");

    response.write(Rsp.nnx(cl));


    response.write("""</option>
""");
  } //for

  response.write("""            </datalist>
            <button type="submit" class="pure-button pure-button-primary">Zobrazit</button>
        </fieldset>
    </form>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
