//Auto-generated by RSP Compiler
//Source: adminGodStudentView.rsp.html
library adminGodStudentView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, adminGodStudentView, for rendering the view. */
Future adminGodStudentView(HttpConnect connect, {var student, dynamic averages, dynamic subjectsDetail}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/adminHead.html");

  response.write("""<div class="content">
    <p>""");

  response.write(Rsp.nnx(student.studentInfo.name));


  response.write(""" (""");

  response.write(Rsp.nnx(student.studentInfo.schoolClass));


  response.write(""")</p>
    <p>""");

  response.write(Rsp.nnx(student.schoolInfo.name));


  response.write("""</p>
    <p>Aktualizováno """);

  response.write(Rsp.nnx(student.refresh.day));


  response.write(""". """);

  response.write(Rsp.nnx(student.refresh.month));


  response.write(""". """);

  response.write(Rsp.nnx(student.refresh.year));


  response.write(""" (Δ""");

  response.write(Rsp.nnx(student.refresh.difference(DateTime.now()).inDays));


  response.write("""d)</p>
    <h1>Průměry</h1>
    <table class="pure-table">
        <tbody>
""");

  for (var subject in averages.keys) {

    response.write("""            <tr>
                <td>
                    <a href="#""");

    response.write(Rsp.nnx(subject));


    response.write("""">""");

    response.write(Rsp.nnx(subject));


    response.write("""</a>
                </td>
                <td>
                    """);

    response.write(Rsp.nnx(averages[subject].toStringAsPrecision(3)));


    response.write("""

                </td>
            </tr>
""");
  } //for

  response.write("""        </tbody>
    </table>
""");

  for (var subject in subjectsDetail) {

    response.write("""    <h2 id=\"""");

    response.write(Rsp.nnx(subject.name));


    response.write("""">""");

    response.write(Rsp.nnx(subject.name));


    response.write("""</h2>
    <table class="grades-table">
        <tr>
            <th>Datum</th>
            <th>Titulek</th>
            <th>Známka</th>
            <th>Váha</th>
        </tr>
""");

    for (var grade in subject.grades) {

      response.write("""        <tr class="grades">
            <td>""");

      response.write(Rsp.nnx(grade.date.day));


      response.write(""". """);

      response.write(Rsp.nnx(grade.date.month));


      response.write("""</td>
            <td>""");

      response.write(Rsp.nnx(grade.caption));


      response.write("""</td>
            <td name="value">""");

      response.write(Rsp.nnx(grade.value.round() == grade.value ? grade.value.toInt() :
                grade.value.floor().toString() + '-'));


      response.write("""</td>
            <td name="weight">""");

      response.write(Rsp.nnx(grade.weight));


      response.write("""</td>
        </tr>
""");
    } //for

    response.write("""    </table>
""");
  } //for

  response.write("""</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
