//Auto-generated by RSP Compiler
//Source: adminLogView.rsp.html
library adminLogView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, adminLogView, for rendering the view. */
Future adminLogView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");

  response.write("""<div class="content">
    <h1>Vizualizace</h1>
    <p>TODO</p>
    <h1>Ke stažení</h1>
    <h2>Logování přímého přístupu</h2>
    <form class="pure-form" action="/admin/log/raw/download" method="POST">
        <fieldset>
            <legend>Vyberte z kolika posledních dnů má být vytvořen soubor ke stažení. -1 znamená kompletní záznam.</legend>
            <input name="days" type="number" value="7" min="-1" max="365" autocomplete="off">
            <button type="submit" class="pure-button pure-button-primary">Stáhnout</button>
        </fieldset>
    </form>
    <h2>Logování přihlášení</h2>
    <form class="pure-form" action="/admin/log/login/download" method="POST">
        <fieldset>
            <legend>Vyberte si z kolika posledních dnů má být vytvořen soubor ke stažení. -1 znamená kompletní záznam.</legend>
            <input name="days" type="number" value="7" min="-1" max="365" autocomplete="off">
            <button type="submit" class="pure-button pure-button-primary">Stáhnout</button>
        </fieldset>
    </form>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
