//Auto-generated by RSP Compiler
//Source: adminLogView.rsp.html
library adminLogView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';
import '../../config.dart';

/** Template, adminLogView, for rendering the view. */
Future adminLogView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");

  response.write("""<div class="content">
    <h1>Vizualizace</h1>
    <p>TODO</p>
    <h1>Ke stažení</h1>
    <p>Vše bude ve formátu JSON.</p>
    <h2>Log přímého přístupu</h2>
    <form class="pure-form" action="/admin/log/raw/download/logRaw" method="GET">
        <fieldset>
            <button type="submit" class="pure-button pure-button-primary">Stáhnout</button>
        </fieldset>
    </form>
    <h2>Log přihlášení studentů</h2>
    <form class="pure-form" action="/admin/log/raw/download/logStudentLogin" method="GET">
        <fieldset>
            <button type="submit" class="pure-button pure-button-primary">Stáhnout</button>
        </fieldset>
    </form>
    <h2>Informace o studentech</h2>
    <form class="pure-form" action="/admin/log/raw/download/logStudentInfo" method="GET">
        <fieldset>
            <button type="submit" class="pure-button pure-button-primary">Stáhnout</button>
        </fieldset>
    </form>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
