//Auto-generated by RSP Compiler
//Source: messageListView.rsp.html
library messageListView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, messageListView, for rendering the view. */
Future messageListView(HttpConnect connect, {int countOfNew, int countOfImportant, Iterable<dynamic> messages}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/adminHead.html");

  response.write("""    <div class="content">
        <h1>Messages</h1>
""");

  if (countOfImportant != 0) {

    response.write("""        <p style="color: red">Important messages: """);

    response.write(Rsp.nnx(countOfImportant));


    response.write("""</p>
""");
  } //if

  if (countOfNew != 0) {

    response.write("""        <p>New messages: """);

    response.write(Rsp.nnx(countOfNew));


    response.write("""</p>
""");
  } //if

  response.write("""        <p>
            <a href="/admin/message">Show only new messages</a> <br />
            <a href="/admin/message/all">Show all messages</a>
        </p>

""");

  for (var message in messages) {

    response.write("""        <div>
            <h2>""");

    response.write(Rsp.nnx(message.subject));


    response.write("""</h2>
            <table>
                <tr>
""");

    if (message.isImportant) {

      response.write("""                    <td style="color: red;">
                        IMPORTANT!
                    </td>
""");
    } //if

    response.write("""                    <td>""");

    response.write(Rsp.nnx(DateTime.now().difference(message.sent).inHours));


    response.write("""h ago</td>
                    <td>
                        """);

    response.write(Rsp.nnx(message.tag));


    response.write("""

                    </td>
                </tr>
            </table>
            <p>
""");

    if (message.text.length <= 120) {

      response.write(""" """);

      response.write(Rsp.nnx(message.getMarkdownInHtml(), encode: 'none'));


    } else {

      response.write(""" """);

      response.write(Rsp.nnx(message.text.substring(0, 120).getMarkdownInHtml(), encode: 'none'));


      response.write(""" ... """);
    } //if

    response.write(""" </p>
                    <p>
                    <a href="/admin/message/""");

    response.write(Rsp.nnx(message.guid));


    response.write("""">View</a>
            </p>
        </div>
        <hr />
""");
  } //for

  response.write("""    </div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
