//Auto-generated by RSP Compiler
//Source: messageView.rsp.html
library messageView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, messageView, for rendering the view. */
Future messageView(HttpConnect connect, {dynamic message}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/adminHead.html");

  response.write("""<div class="content">
    <h1>""");

  response.write(Rsp.nnx(message.subject));


  response.write("""</h1>
    <table>
        <tr>
""");

  if (message.isImportant) {

    response.write("""            <td style="color: red;">
                IMPORTANT!
            </td>
""");
  } //if

  response.write("""            <td>""");

  response.write(Rsp.nnx(DateTime.now().difference(message.sent).inHours));


  response.write("""h ago</td>
            <td>
                """);

  response.write(Rsp.nnx(message.tag));


  response.write("""

            </td>
        </tr>
    </table>
    <p>
        """);

  response.write(Rsp.nnx(message.getMarkdownInHtml(), encode: 'none'));


  response.write("""

    </p>
    <hr />
    <p>
""");

  if (message.email != '') {

    response.write("""        <a href="mailto: """);

    response.write(Rsp.nnx(message.email));


    response.write("""">""");

    response.write(Rsp.nnx(message.email));


    response.write("""</a>
""");
  } //if

  response.write("""    </p>
""");

  if (!message.isClosed) {

    response.write("""    <form class="pure-form" action="/admin/message/markAsRead/""");

    response.write(Rsp.nnx(message.guid));


    response.write("""" method="POST">
        <button type="submit" class="pure-button pure-button-primary">Mark as solved</button>
    </form>
""");
  } //if

  response.write("""    <a href="/admin/message">Back</a>
</div>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
