//Auto-generated by RSP Compiler
//Source: contact.rsp.html
library contact_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, contactView, for rendering the view. */
Future contactView(HttpConnect connect, {bool showSuccMessage, String errorMessage}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");

  if (showSuccMessage) {

    response.write("""<div class="successBar">
    <p>Zpráva byla odeslána!</p>
</div>
""");
  } //if

  if (errorMessage != null) {

    response.write("""<div class="errorBar">
    <p>""");

    response.write(Rsp.nnx(errorMessage));


    response.write("""</p>
</div>
""");
  } //if

  response.write("""

<div class="content">
    <h1>Kontakt</h1>
    <p>
        Je možné mě kontaktovat pomocí následujícího formuláře.
        Pokud to bude potřeba, pošlu vám zpátky odpověď emailem.
    </p>
    <form class="pure-form" action="/contact" method="POST">
        <fieldset>
            <legend><a href="/privacy_policy">Zpracování osobních údajů</a></legend>

            <label for="subject">Nadpis *</label>
            <input type="text" id="subject" name="subject">
            <br />

            <label for="type">Typ zprávy *</label>
            <select type="text" id="type" name="messageType">
                <option value="bug">Nahlášení chyby</option>
                <option value="featureRequest">Návrh na novou funkci</option>
                <option value="featureRequest">Ostatní</option>
            </select>
            <br />

            <label for="important">Je to důležité!</label>
            <input type="checkbox" id="important" name="isMessageImportant">
            <br />

            <label for="body">Zpráva *</label>
            <textarea id="body" name="messageBody"></textarea>
            <br />

            <label for="email">Email</label>
            <input type="email" id="email" name="email">
            <br />

            <button type="submit" class="pure-button pure-button-primary">Odeslat</button>
        </fieldset>
    </form>
    <p>
        Po zaškrtnutí políčka "Je to důležité!" se pokusím zprávu vyřešit co nejdříve.
    </p>
    <p>
        Používejte toto políčko pouze když je to opravdu nutné, například
        když objevíte na webu zranitelnost.
    </p>
    <p>
        Email je potřeba vyplnit pouze pokud očekáváte odpověď. Je nutné
        ho vyplnit pokud označíte zprávu jako důležitou.
    </p>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
