//Auto-generated by RSP Compiler
//Source: lubosView.rsp.html
library lubosView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, lubosView, for rendering the view. */
Future lubosView(HttpConnect connect, {dynamic cites}) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");

  response.write("""

<div class="content">
  <h1>Lubošova moudra</h1>
  <table class="lubos-table">
      <tr>
          <th>Datum</th>
          <th>Moudro</th>
      </tr>
""");

  for (var cite in cites) {

    response.write("""      <tr>
          <td>""");

    response.write(Rsp.nnx(cite[0]));


    response.write("""</td>
          <td>""");

    response.write(Rsp.nnx(cite[1]));


    response.write("""</td>
      </tr>
""");
  } //for

  response.write("""  </table>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
