//Auto-generated by RSP Compiler
//Source: privacyPolicyView.rsp.html
library privacyPolicyView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';
import '../../config.dart';
import '../../tools/tools.dart';

/** Template, privacyPolicyView, for rendering the view. */
Future privacyPolicyView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");
var sessionCookieLength = Tools.daysToStringWithUnit(Config.daysHowLongIsSessionCookieStored);
var classCookieLength = Tools.daysToStringWithUnit(Config.daysHowLongIsClassIdentifierCookieStored);

  response.write("""


<div class="content">
  <h1>Ochrana osobních údajů a cookies</h1>
  <p>
    Přihlášením na web předáváte své přihlašovací údaje na zpracování tomuto serveru. Server k nim má přístup pouze po
    dobu zpracování Vašeho požadavku.
  </p>
  <p>
    Dočasně ukládáme na serveru informace přijaté ze serveru školy, abychom je mohli průběžně zobrazovat. Přístupový
    kód k těmto údajům ukládáme ve vašem prohlížeči v souboru cookie. Tento přístupový kód
    bude ve vašem prohlížeči uložen """);

  response.write(Rsp.nnx(sessionCookieLength));


  response.write(""" nebo dokud se neodhlásíte.
  </p>
  <p>
    Informace přijaté ze serveru školy, jako třeba známky nebo rozvrh, jsou bezpečně zašifrované - nikdo kromě vás se k
    nim nedostane.
  </p>
  <p>
    Po přihlášení uložíme do vašeho prohlížeče URI bakalářů vaší školy a vaše přihlašovací jméno, takže nemusíte při
    každém přihlášení znovu tyto informace zadávat. Tyto informace budou po každém novém přihlášení uloženy na """);

  response.write(Rsp.nnx(classCookieLength));


  response.write(""".
  </p>
  <p>
    Pokud kontaktujete administrátora této stránky (<a href="/contact">zde</a>), na dobu neurčitou uložíme
    váš email, pokud ho vyplníte.
  </p>
  <p>
    Zaznamenáváme informace o připojení se na tento web z důvodu tvorby hezkých barevných grafů. Ukládáme zahashovanou
    IP adresu. Žádné vaše informace nikdy nebudou přístupny třetím stranám (vyjma systému vaší školy při prihlašování).
  </p>
  <p>
    Tento text byl naposledy změněn 2019-03-06.
  </p>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
