//Auto-generated by RSP Compiler
//Source: restApi.rsp.html
library restApi_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, restApiView, for rendering the view. */
Future restApiView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");

  response.write("""<div class="content">
    <h1>Oficiální API</h1>
    <p>
        Tato webová aplikace získává data pomocí
        knihovny <a href="https://pub.dartlang.org/packages/bakalari">bakalari</a> (<a href="https://www.dartlang.org/">Dart</a>).
        Tato knihovna
        je veřejně k dispozici, zcela zdarma. Zdrojový kód
        je k dispozici na <a href="https://github.com/soptikha2/bakalari">GitHubu</a>.
    </p>
    <p>
        Existují i další knihovny, například knihovna
        <a href="https://github.com/vakabus/pybakalib/">pybakalib</a> pro python, ze které má Dart knihovna vychází.
    </p>
    <p>
        API školního systému Bakaláři je shrnuto v <a href="https://github.com/bakalari-api/bakalari-api">tomto
            repozitáři.</a>
    </p>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
