//Auto-generated by RSP Compiler
//Source: torView.rsp.html
library torView_rsp;

import 'dart:async';
import 'dart:io';
import 'package:stream/stream.dart';

/** Template, torView, for rendering the view. */
Future torView(HttpConnect connect) async {
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return null;

  await connect.include("/webapp/view/templates/head.html");

  response.write("""<div class="content">
    <h1>Tor</h1>
    <img src="/other/onion-icon.png" />
    <p>
        Tato webová služba umožňuje připojení pomocí anonymní sítě Tor.
    </p>
    <a href="http://vwmiumqnxnfclfdu.onion:8888/" target="_blank"><button
            class="pure-button pure-button-primary">vwmiumqnxnfclfdu.onion:8888</button></a>
</div>
""");

  await connect.include("/webapp/view/templates/tail.html");

  return null;
}
